#!/bin/bash
 
TARGET="C:\devtools\Apache24\htdocs\my-app1"
GIT_DIR="C:\React-basics\my-app\.git"
BRANCH="dev"
 
while read oldrev newrev ref
do
    # Only deploy when the dev branch is updated
    if [[ $ref = "refs/heads/$BRANCH" ]]
    then
        echo "Deploying $BRANCH branch..."
         
        # Check out the latest version of the dev branch
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout $BRANCH -f
         
        export NODE_ENV=production

        # Install dependencies and build the app
        cd $TARGET
        npm install
        npm run build
         
        rsync -avz --delete build/ I556802@localhost:/devtools/Apache24/htdocs/my-app

        # Stop and restart Apache
        "C:\devtools\Apache24\bin\httpd.exe" -k stop
        "C:\devtools\Apache24\bin\httpd.exe" -k start

        echo "Deployment complete."
    fi
done
