#!/bin/bash

TARGET="C:\devtools\Apache24\htdocs\my-app2"
GIT_DIR="C:\React-basics\my-app\.git"
BRANCH="dev"
HTTPD_PATH="C:\devtools\Apache24\bin\httpd.exe"
 
while read oldrev newrev ref
do
    # Only deploy when the dev branch is updated
    if [[ $ref = "refs/heads/$BRANCH" ]]
    then
        echo "Deploying $BRANCH branch..."
         
        # Check out the latest version of the dev branch
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout $BRANCH -f
         
        export NODE_ENV=production

        # Install dependencies and build the app
        cd $TARGET
        npm install
        npm run build

        # Copy the contents of the build folder to Apache's htdocs folder
        cp -R build/* "C:\devtools\Apache24\htdocs\my-app2"

        # Restart Apache
        $HTTPD_PATH -k restart

        echo "Deployment complete."
    fi
done
